name: Build

on:
  push:
    branches:
    - main

jobs:
  build-job:
    name: Build Job 1
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - uses: actions/checkout@2
        with:
          fetch-depth: 0
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
